# Generated by Django 4.0.4 on 2022-05-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_review_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='music',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music.music'),
            preserve_default=False,
        ),
    ]
