# Generated by Django 4.0.4 on 2022-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
