# Generated by Django 4.0.4 on 2022-05-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_reviews_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='album',
            new_name='music',
        ),
    ]
