# Generated by Django 4.0.4 on 2022-05-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_review_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music.music'),
        ),
    ]
