# Generated by Django 4.0.5 on 2022-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('COU', 'Course'), ('AL', 'Album'), ('CON', 'Consulting')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('V', 'Very'), ('S', 'Standart'), ('L', 'Low')], default=2, max_length=1),
            preserve_default=False,
        ),
    ]
