# Generated by Django 4.0.5 on 2022-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('S', 'Success'), ('P', 'Primary'), ('W', 'Warning')], max_length=1),
        ),
    ]
