# Generated by Django 4.0.5 on 2022-06-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
